### ISSUE TITLE
Issue of allignment of search bar. Can anyone fix this

### ISSUE THREAD

**Issue by GulamMd** [GulamMd/grid-skeleton-loader#1]
In the header section search bar is not properly alligned can anyone fix this issue

**Comment by hemantwasthere** [comment]
Hey @GulamMd, I would like to work on this issue

**Comment by GulamMd** [comment]
Yeah please i have assigned it to you

**Comment by Oceaneyes123** [comment]
Hello @GulamMd, since this issue is still not fixed until now, can you assign it to me? 
I'll send a pull request right away. Thanks

**Comment by Oceaneyes123** [comment]
Hello @GulamMd , I already created pull request #3  as a fix for this issue.

Thanks!

**Comment by GulamMd** [comment]
Thank you for your valuable work...

**Comment by GulamMd** [comment]
@Oceaneyes123 Brother there is one more problem of alignment happening in the UI when we refresh, conatainer size decreases ,shimmer is not in perfect sync we need to just set the alignment properly to every row when there is loading true...But i don't know why it is not working in my computer if i set any number of pixels... So Can you look into that problem once?

**Comment by Oceaneyes123** [comment]
can you add, ***hacktoberfest-accepted*** tag in this issue?  this would greatly help. Thanks

@GulamMd

**Comment by Oceaneyes123** [comment]
And @GulamMd, can you elaborate the steps to reproduce the issue/error. Because I think, it's working fine in my end

**Comment by GulamMd** [comment]
So the problem is when i reload the page the skeleton loaders alignment to all the item text doesn't match i.e the whole container size of skeleton loader and normal content table's container size is different it is creating a shaking effect of increasing and decreasing the whole page

**Comment by Oceaneyes123** [comment]
@GulamMd Please check PR #4

**Comment by GulamMd** [comment]
Yeah accepted ... Great Work.
Thank You
